---
title: "Yelp-Dataset-Project"
author: "Ana Perez, Clarissa Vazquez, Naelin Aquino"
date: "May 10, 2017"
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(prompt=TRUE, comment="", echo=TRUE)
```

```{r}
#preparing the datasets
source("process-data.r")
library(FNN)
library(class)

fnames = c('business','checkin','review','tip','user')
jfile = paste0('~/yelp_dataset_challenge_round9/yelp_academic_dataset_',fnames,'.json')
user_dat = user_data(jfile[5])


#scale user data


```

## User Data Exploration

```{r}
hist(user_dat$elite[user_dat$elite != 0], xlab = "years", ylab = "people", main="Elite Yelpers", col = "purple", xlim = c(2, 13))
```

Pictured in this histogram is the amount of years a Yelp user has been an Elite Yelper. An Elite Yelper is someone who gives well-written reviews, high quality tips, have a detailed personal profile, an active voting and complimenting record, and a history of playing well with others. Out of 1029432 about 44246 yelpers are Elite. 

## KNN Regression Model

```{r}
# KNN REGRESSION
#data split for training and testing
tr_rows = 1:floor(nrow(user_dat)*.70)
# features to be used
features = c("useful", "review_count")
# feature vectors training and testing data
fvs = user_dat[,features]
tr_dat = fvs[tr_rows,]
te_dat = fvs[-tr_rows,]

average_stars = user_dat[,"average_stars"]
tr_average_stars = average_stars[tr_rows]
te_average_stars = average_stars[-tr_rows]

actuals = round(te_average_stars)
predicts = knn.reg(tr_dat, te_dat, tr_average_stars, k=11)
predicts$pred = round(predicts$pred)

table(actuals, predicts$pred)
```

